cmake_minimum_required(VERSION 3.8)
project(astribot_nav_sensors)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(diagnostic_msgs REQUIRED)
find_package(tf2_ros REQUIRED)
find_package(tf2_sensor_msgs REQUIRED)
add_executable(scan_processor src/scan_processor.cpp)
target_compile_features(scan_processor PUBLIC cxx_std_17)
ament_target_dependencies(scan_processor rclcpp sensor_msgs diagnostic_msgs tf2_ros tf2_sensor_msgs)
install(TARGETS scan_processor DESTINATION lib/${PROJECT_NAME})
ament_package()
